---
title: Text Analysis  - Moby Dick
author: Alan Ryan
date: '2018-02-20'
slug: text-analysis-moby-dick
categories: []
tags: []
---
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidytext)
library(gutenbergr)
library(tidyverse)
library(stringr)
library(wordcloud)
```
#Moby Dick text analysis
##1. Word frequency:

First download the book from [Project Gutenberg](https://www.gutenberg.org/)

```{r echo=FALSE, message=FALSE}
moby <- gutenberg_download(2489) %>%
        mutate(linenumber = row_number(),
               chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]",
                                                       ignore_case = TRUE))))
select(moby, -gutenberg_id)
```

Then, tidy the text

```{r echo=FALSE, message=FALSE}
tidy_moby <- moby  %>%
        unnest_tokens(word, text) %>% 
        select(-gutenberg_id)
knitr::kable(head(tidy_moby, n=10), align=c(rep('c', 5)))
```

Next, remove the stop words

```{r echo=FALSE, message=FALSE}
data(stop_words)

tidy_moby <- tidy_moby %>%
        anti_join(stop_words)%>%
        count(word, sort = TRUE)
```

Find the most common words in the book and display them in a word cloud:

```{r echo=FALSE, results='hide'}
with(tidy_moby, wordcloud(word, n, max.words = 100))
```
